services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TOKEN
        value: "8599078171:AAE4YSTeZv0Z1ZL0EAVM_LHJNeS_NKZGTBY"
      - key: ADMIN_ID
        value: "903089622"